[project]
name = "advent-of-code-2024"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aoc-glue",
    "numpy>=2.1.3",
    "tqdm>=4.67.1",
]

[dependency-groups]
dev = [
    "ruff>=0.8.1",
]

[tool.uv.sources]
aoc-glue = { path = "aoc-glue" }
